#define DISPLAY_WIDTH 128
#define DISPLAY_HEIGHT 64

#define BATTERY_FULL_VALUE 270
#define BATTERY_EMPTY_VALUE 210

// UI positions
#define METERING_MODE_X 2
#define METERING_MODE_Y 8
#define ISO_VALUE_X 18
#define ISO_VALUE_Y 8
#define LX_VALUE_X 72
#define LX_VALUE_Y 8
#define BATTERY_X 121
#define BATTERY_Y 1

#define HEADER_SEPARATOR_START_X 0
#define HEADER_SEPARATOR_START_Y 11
#define HEADER_SEPARATOR_END_X 127
#define HEADER_SEPARATOR_END_Y 11

#define F_ICON_X 19
#define F_ICON_Y 30
#define F_VALUE_X 42
#define F_VALUE_Y 30
#define F_INDICATOR_X 10
#define F_INDICATOR_Y 27

#define T_ICON_X 19
#define T_ICON_Y 50
#define T_VALUE_X 42
#define T_VALUE_Y 50
#define T_INDICATOR_X 10
#define T_INDICATOR_Y 47

#define EV_ICON_X 97
#define EV_ICON_Y 23
#define EV_VALUE_X 97
#define EV_VALUE_Y 33

#define ND_ICON_X 97
#define ND_ICON_Y 43
#define ND_VALUE_X 109
#define ND_VALUE_Y 43
#define ND_VALUE_2_X 97
#define ND_VALUE_2_Y 52

#define EV_SEPARATOR_START_X 93
#define EV_SEPARATOR_START_Y 16
#define EV_SEPARATOR_END_X 93
#define EV_SEPARATOR_END_Y 53

#define MENU_ISO_TITLE_X 51
#define MENU_ISO_TITLE_Y 17
#define MENU_ISO_VALUE_X 64
#define MENU_ISO_VALUE_Y 50

#define MENU_ND_TITLE_X 11
#define MENU_ND_TITLE_Y 17
#define MENU_ND_VALUE_X 64
#define MENU_ND_VALUE_Y 50
