#define FONT_STANDARD u8g2_font_profont10_mr
#define FONT_H1 u8g2_font_10x20_mr
#define FONT_H2 u8g2_font_10x20_mr

// UI positions
#define METERING_MODE_X 120
#define METERING_MODE_Y 27

#define ISO_ICON_X 81
#define ISO_ICON_Y 7
#define ISO_VALUE_X 97
#define ISO_VALUE_Y 7

#define LX_ICON_X 81
#define LX_ICON_Y 15
#define LX_VALUE_X 97
#define LX_VALUE_Y 15

#define BATTERY_X 120
#define BATTERY_Y 3

#define HEADER_SEPARATOR_START_X 78
#define HEADER_SEPARATOR_START_Y 0
#define HEADER_SEPARATOR_END_X 78
#define HEADER_SEPARATOR_END_Y 31

#define F_ICON_X 8
#define F_ICON_Y 14
#define F_VALUE_X 19
#define F_VALUE_Y 14
#define F_INDICATOR_X 1
#define F_INDICATOR_Y 12

#define T_ICON_X 8
#define T_ICON_Y 30
#define T_VALUE_X 19
#define T_VALUE_Y 30
#define T_INDICATOR_X 1
#define T_INDICATOR_Y 26

#define EV_ICON_X 81
#define EV_ICON_Y 23
#define EV_VALUE_X 97
#define EV_VALUE_Y 23

#define ND_ICON_X 81
#define ND_ICON_Y 31
#define ND_VALUE_X 97
#define ND_VALUE_Y 31
#define ND_VALUE_2_X -1
#define ND_VALUE_2_Y -1

#define EV_SEPARATOR_START_X 117
#define EV_SEPARATOR_START_Y 0
#define EV_SEPARATOR_END_X 117
#define EV_SEPARATOR_END_Y 31

#define MENU_ISO_TITLE_X 2
#define MENU_ISO_TITLE_Y 22
#define MENU_ISO_TITLE_TEXT F("ISO")
#define MENU_ISO_VALUE_X 42
#define MENU_ISO_VALUE_Y 22

#define MENU_ND_TITLE_X 2
#define MENU_ND_TITLE_Y 22
#define MENU_ND_TITLE_TEXT F("ND")
#define MENU_ND_VALUE_X 33
#define MENU_ND_VALUE_Y 22

#define MENU_DEBUG_TITLE_X 2
#define MENU_DEBUG_TITLE_Y 22
#define MENU_DEBUG_TITLE_TEXT F("DBG")
#define MENU_DEBUG_VALUE_X 33
#define MENU_DEBUG_VALUE_Y 22

#define SEPARATOR_3_START_X 119
#define SEPARATOR_3_START_Y 15
#define SEPARATOR_3_END_X 127
#define SEPARATOR_3_END_Y 15

#define NOTIFICATION_METERING_VALUE_X 5
#define NOTIFICATION_METERING_VALUE_Y 23
#define NOTIFICATION_METERING_TEXT F(" Measuring! ")
